name: CI testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-ci-testing:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Go
        run: go version

      - name: Create .env from secrets
        shell: bash
        run: |
          printf "SERVER_PORT=%s\n" "${{ secrets.SERVER_PORT }}" > .env
          printf "DB_HOST=%s\n" "${{ secrets.DB_HOST }}" >> .env
          printf "DB_PORT=%s\n" "${{ secrets.DB_PORT }}" >> .env
          printf "DB_NAME=%s\n" "${{ secrets.DB_NAME }}" >> .env
          printf "DB_USER=%s\n" "${{ secrets.DB_USER }}" >> .env
          printf "DB_PASSWORD=%s\n" "${{ secrets.DB_PASSWORD }}" >> .env
          printf "DB_SSLMODE=%s\n" "${{ secrets.DB_SSLMODE }}" >> .env
          printf "JWT_SECRET_KEY=%s\n" "${{ secrets.JWT_SECRET_KEY }}" >> .env

      - name: Start containers
        run: docker compose up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          until docker exec postgres-db pg_isready -U "$DB_USER" -d "$DB_NAME"; do
            sleep 2
          done
          echo "PostgreSQL is ready"

      - name: Build Go application
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
