name: CI testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-ci-testing:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Go
        run: go version
      - name: Start containers
        run: docker compose up -d --build
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          until docker exec postgres-db pg_isready -U "$DB_USER" -d "$DB_NAME"; do
            sleep 2
          done
          echo "Ready"
      - name: Build
        run: go build -v ./...
      - name: Run tests
        run: go test -v ./...
